### PR TITLE
Ebean refactor

### PR DESCRIPTION
**Pull request by JoaoRoxoNeves**

### CODE REVIEW

**Comment by ajcamilo** [comment]
I'll give you 200 kudos if you change the package from `jpa` to `ebean`.

**Comment by madskaddie** [comment]
Que eh isto? Isto tem impacto no código existente...

**Comment by ajcamilo** [comment]
@madskaddie it's another project, no changes were made to the `billy-core-jpa` project.

**Comment by ajcamilo** [comment]
Just another thing, can you change the version to 3.1.0-SNAPSHOT?

**Comment by JoaoRoxoNeves** [comment]
@ajcamilo Done.

**Pull request merged**
